### ISSUE TITLE
Simple Configuration File for Tin Can Phone

### ISSUE THREAD

**Issue by mgoldenberg** [dmahfouda/tin-can-phone#3]
Configuration options should exist in a separate file than `tin-can-phone.ino`. They should be defined in a `.h` file using preprocessor directives and then included in `tin-can-phone.ino`. See example below.

```
// tin-can-phone.ino
#include "config.h"

void setup() {
    can.connectToWifi(TIN_CAN_SSID, TIN_CAN_PASSWORD);
}
```

```
// config.h
#define TIN_CAN_SSID "ssid"
#define TIN_CAN_PASSWORD "password"
```

Configurations options should minimally include:

- `TIN_CAN_SSID` - the WiFi network to connect to
- `TIN_CAN_PASSWORD` - the WiFi password
- `TIN_CAN_ID` - the name of the can
- `TIN_CAN_SWITCH` - the url of the switching server

Others may present themselves, but these would be helpful for now.

**Comment by dmahfouda** [comment]
@mgoldenberg so the config.h file will be typically ignored in git... but is there an initial way to commit it to the code base and then ignore it thereafter?

**Comment by dmahfouda** [comment]
The goals are to be able to not change hard-coded values in our repository, and also potentially to avoid long compile times.
